os: linux
dist: trusty

language: bash

services:
  - docker

before_install:
  - docker build --pull --rm -f "Dockerfile" -t dcr-trinitycore:latest .

install:
  - docker run --rm -it -v /root/compiled:/root/compiled dcr-trinitycore:latest